---
title: "Distributions_check"
output: html_document
---
```{r}
library(bigsnpr)
library(dplyr)
```


```{r}
G1 = snp_attach("test_sim1.rds")
G2 = snp_attach("test_fbm.rds")
G3 = snp_attach("LTFH.rds")
```

```{r}
Simple_test = function(info){
  # Get information
  G = info$genotypes
  MAF = info$map$MAF
  l_g = info$fam$l_g
  l_e = info$fam$l_e
  y = info$fam$y
  
  l = l_g + l_e 
  qqnorm(l)
  print(c('mean'=mean(l),'variance'=var(l)))
  
  }
```

```{r}
Simple_test(G1)
```

```{r}
Simple_test(G2)
```




```{r}
LT_FH_test = function(){
  
}
```




```{r}


l_g = G3$fam$l_g
l_e = G3$fam$l_e
l_g1 = G3$fam$l_g1
l_e1 = G3$fam$l_e1
l_g2 = G3$fam$l_g2
l_e2 = G3$fam$l_e2
```


```{r}
# Check if mean of G is correct
G_mean = colMeans(G[,])
MAF_mean = MAF*2

all.equal.numeric(G_mean, MAF_mean, tolerance= .Machine$double.eps ^ 0.5, scale=NULL)
G_mean[1:10]
MAF_mean[1:10]

```



```{r}
# Check distribution of liability (standard normal)
l1 = l_g1 + l_e1 
qqnorm(l1)
mean(l1)
var(l1)
```


```{r}
# Check sum of y (expect K)
mean(y)
```


