---
title: "Distributions_check_functions"
output: html_document
---

```{r}
library(bigsnpr)
library(dplyr)
```


```{r}
G1 = snp_attach("test_sim2.rds")
G2 = snp_attach("test.rds")
```

```{r}
y_func = function(l_e_0, l_g_0, K=0.05) {
  l_0 = l_g_0 + l_e_0
  T_ = qnorm(1-K)
  y = ifelse(l_0>=T_, 1, 0)
  return(y)
}
```

```{r}
get_names <- function(values, n_sib=0, id= TRUE, parents=TRUE){
  
  len = length(values)
  prefix = c(rep("", len*id), rep("p",len*2*parents), rep("s",n_sib*len))
  
  n_peop = 1*id + 2*parents + n_sib
  index = c(rep(0,id), rep(c(1:2),parents), rep(c(3:(2+n_sib)),n_sib!=0))
  
  name = rep("", len*(n_peop))
  j = 1
  for (i in 1:n_peop){
    name[j:(j+len-1)] = paste0((paste(values,prefix[j:(j+len-1)], sep="_")), rep(index[i], len))
    j = j + len
  }
  return(name)
}
```

```{r}
Simple_test = function(info){
  # Get information
  G = info$genotypes
  MAF = info$map$MAF
  l_g = info$fam$l_g
  l_e = info$fam$l_e
  y = info$fam$y
  
  l = l_g + l_e 
  qqnorm(l)
  print(c('mean l'=mean(l),'variance l'=var(l), 'mean y'=mean(y)))
  
  }
```

```{r}
LT_FH_test = function(info){
  l_g = info$fam$l_g_0
  l_e = info$fam$l_e_0
  l_g1 = info$fam$l_g_p1
  l_e1 = info$fam$l_e_p1
  l_g2 = info$fam$l_g_p2
  l_e2 = info$fam$l_e_p2
  l_g3 = info$fam$l_g_s3
  l_e3 = info$fam$l_e_s3
  
  l = l_g + l_e
  l1 = l_g1 + l_e1
  l2 = l_g2 + l_e2
  l3 = l_g3 + l_e3
  par(mfrow=c(1,3))
  qqnorm(l)
  qqnorm(l1)
  qqnorm(l2)
  print(c('mean l'=mean(l),'variance l'=var(l)))
  print(c('mean l1'=mean(l1),'variance l1'=var(l1)))
  print(c('mean l2'=mean(l2),'variance l2'=var(l2)))
    print(c('s3 l3'=mean(l3),'variance l3'=var(l3)))

}
```



```{r}
sim_test = function(info){
l = list()
c = 0
for (i in G2$fam){
  c = c + 1
  if (c != 1){
    if (c %% 2 == 0){
      l[[c-(c/2)]] = i
    }
    else{
      l[[c - ((c-1)/2)-1]] = l[[c - ((c-1)/2)-1]] + i
    }
  }
}
par(mfrow=c(1,length(l)))
for (j in l){
  qqnorm(j)
}
c = 0
for (j in l){
  out = c(mean(j), var(j))
  names(out) = c(sprintf("mean_l%s", c), sprintf("variance_l%s", c))
  print(out)
  c = c + 1
}
}
```

```{r}
sim_test(G2)
```
```{r}
k = list()
k[[1]] = 2
k
```


