---
title: "Gibb3"
output: html_document
---

```{r}
get_cov = function(h2, n_sib = 0) {
  cov <- matrix(h2/2, 4 + n_sib, 4 + n_sib)
  diag(cov) <- 1
  cov[3,4] <- cov[4,3] <- 0
  cov[1:2, 1] <- cov[1, 1:2] <- h2
  cov
}
```


```{r}
calc_distribution = function(sigma){
  out = list()
  for (i in 1:nrow(sigma)){
    mu_mult_bar = solve(sigma[ -i, -i], sigma[i , -i])
    sigma_bar = sigma[i,i] - mu_mult_bar %*% sigma[-i , i]
    out[[i]] = list('sigma'=sigma_bar, 'mu_mult'=mu_mult_bar)
    }
  return(out)
  }
```


```{r}
# Vores gibbssampler


Gibb <- function(covmat, phenos, N, K= 0.05){
  
  s_val = 0
  
  k = nrow(covmat)

  const_list = calc_distribution(covmat)
  
  liabil = matrix(s_val, nrow = N, ncol = k) # i formen c(l_g, l, l_p1, l_p2)
  mu_vec = matrix(s_val, nrow = N, ncol = k)
  
  current_liabil = rep(s_val, k)
  
  
  
  for (i in 2:N) {
    for (j in 1:k) {
      # Udregner parametre
      sigma = const_list[[j]]$sigma
      mu_mult_ = const_list[[j]]$mu_mult
      mu = mu_mult_ %*% current_liabil[-j] # Udelukker den liability vi er kommet til
    
      mu_vec[i,j] = mu
      
      if (j == 1) {
        current_liabil[j] = rnorm(1, mu, sqrt(sigma))
      }
      else {
        crit <- qnorm(1-K)
        crit_bound = pnorm(crit, mu, sqrt(sigma))
        
        interval_2 = c(0, crit_bound)
        interval_1 = c(crit_bound, 1)
        
        phen = phenos[j-1]
        interval = phen * interval_1 + (1-phen)*interval_2
        U = runif(1,interval[1], interval[2])
        current_liabil[j] = qnorm(U, mu, sqrt(sigma))
      }
      
      
    }
    liabil[i,] = current_liabil
  }
  return(list('liabilities'=liabil, 'mu'=mu_vec))
}
```



```{r}
covmat = get_cov(0.5)
test=Gibb(covmat, c(1,1,1), N=10000)

par(mfrow=c(2,2))
plot(test$liabilities[,1], type='l')
plot(test$liabilities[,2], type='l')
plot(test$liabilities[,3], type='l')
plot(test$liabilities[,4], type='l')
```


```{r}
par(mfrow=c(2,2))
plot(test$mu[,1], type='l')
plot(test$mu[,2], type='l')
plot(test$mu[,3], type='l')
plot(test$mu[,4], type='l')
```




```{r}
Gibb_notrunc <- function(covmat, N, T_ = 0.05){

  k = nrow(covmat)

  const_list = calc_distribution(covmat)

  liabil = matrix(0, nrow = N, ncol = k) # i formen c(l_g, l, l_p1, l_p2)
  mu_vec = matrix(0, nrow = N-1, ncol = k)
  current_liabil = rep(0, k)

  for (i in 1:(N-1)) {
    for (j in 1:k) {
      # Udregner parametre
      sigma = const_list[[j]]$sigma
      mu_mult = const_list[[j]]$mu_mult
      mu = mu_mult %*% current_liabil[-j] # Udelukker den liability vi er kommet til
      mu_vec[i,j] = mu
      current_liabil[j] = rnorm(1, mu, sqrt(sigma))
    }
    liabil[i,] = current_liabil
  }
  return(list('liabilities'=liabil, 'mu'=mu_vec))
}
```

```{r}
test2 = Gibb_notrunc(get_cov(0.5), 3000)
```

```{r}
plot(test$liabilities[,3], test$liabilities[,4], col=2, pch=20)
```



