---
title: "LT-FH-sample"
output: html_document
---

```{r}
library(bigsnpr)
library(dplyr)

#M = 1e5
#N = 1e5
M = 10000
N = 10000

G = FBM.code256(nrow = N,
                ncol = M,
                code = c(0L, 1L, 2L, rep(NA_integer_, 256 - 3)),
                backingfile = "LTFH")


```





```{r}
# Make MAF
MAF = runif(M, 0.01, 0.49)


# Make beta
h_sq = 0.5
C = 100
#C = 1000
beta = rep(0, M)
beta[sample(M,C)] = rnorm(C, 0, sqrt(h_sq/C))

l_g1 = rep(0, M)
l_g2 = rep(0, M)


# Make G
block_size = 100
# block_size = 1000
iterations = M/block_size
current_start = 1

for(i in 1:iterations){
  current_start = (i-1) * block_size + 1
  current_end = current_start + block_size - 1
  
  probs = MAF[current_start:current_end]
  beta_cut = beta[current_start:current_end]
  
  G1 = matrix(rbinom(block_size*N, 2, MAF), ncol=block_size, nrow=N, byrow = T)
  G2 = matrix(rbinom(block_size*N, 2, MAF), ncol=block_size, nrow=N, byrow = T)
  k = matrix(rnorm(block_size*N, 0, 0.0000001), ncol=block_size, nrow=N, byrow = T)
  
  G[,current_start:current_end] = round((G1 + G2)/2 - k)
  
  l_g1 = l_g1 + c(sweep(sweep(G1[,], FUN = '-', STATS=2*probs, MARGIN = 2), FUN='/',
                                           STATS=sqrt(2*probs*(1-probs)), MARGIN = 2)  %*% beta_cut)
  l_g2 = l_g2 + c(sweep(sweep(G2[,], FUN = '-', STATS=2*probs, MARGIN = 2), FUN='/',
                                           STATS=sqrt(2*probs*(1-probs)), MARGIN = 2)  %*% beta_cut)
  
  }


```



```{r}
# Make liabilities
l_g = rep(0, N)
block_size = 1000
iterations = N/block_size
current_start = 1


for (i in 1:iterations){
  current_end = current_start + block_size - 1
  l_g[current_start:current_end] = c(sweep(sweep(G[current_start:current_end,], FUN = '-', STATS=2*MAF, MARGIN = 2), FUN='/',
                                           STATS=sqrt(2*MAF*(1-MAF)), MARGIN = 2)  %*% beta)
  current_start = current_start + block_size
}
  

l_e = rnorm(N, 0, sqrt(1-h_sq))
l = l_g + l_e


# Calculate who is sick
K = 0.05
T_ = qnorm(1-K)
y = ifelse(l>=T_, 1, 0)


l_e1 = rnorm(N, 0, sqrt(1-h_sq))
l_e2 = rnorm(N, 0, sqrt(1-h_sq))

```




```{r}

obj.bigsnp_LTFH = list(genotypes = G, # genotypes, FBM object
                  map = tibble(snp = 1:ncol(G), MAF, beta), # map, i.e. SNP info
                  fam = tibble(FID = 1:nrow(G), l_g, l_e, l_g1, l_e1, l_g2, l_e2)) # fam, i.e. info on individuals

#saving the bigsnp object
snp_save(obj.bigsnp_LTFH)

```


