---
title: "Simulation_parents"
output: html_document
---

```{r}
library(bigsnpr)
library(dplyr)
```


```{r}
# Make beta
beta_func = function(C=1000, h_sq=0.5, M=1e5){
  beta = rep(0, M)
  beta[sample(M,C)] = rnorm(C, 0, sqrt(h_sq/C))
  return (beta)
}

```


```{r}
# Make G
G_func = function(filename, MAF, N=1e5, M=1e5, block_size=1000){
  G = FBM.code256(nrow = N,
                    ncol = M,
                    code = c(0L, 1L, 2L, rep(NA_integer_, 256 - 3)),
                    backingfile = filename)
  
  
  l_g1 = rep(0, M)
  l_g2 = rep(0, M)
  
  iterations = M/block_size
  for(i in 1:iterations){
    current_start = (i-1) * block_size + 1
    current_end = current_start + block_size - 1
  
    probs = MAF[current_start:current_end]
    beta_cut = beta[current_start:current_end]
  
    G1 = matrix(rbinom(block_size*N, 2, MAF), ncol=block_size, nrow=N, byrow = T)
    G2 = matrix(rbinom(block_size*N, 2, MAF), ncol=block_size, nrow=N, byrow = T)
    k = matrix(rnorm(block_size*N, 0, 0.0000001), ncol=block_size, nrow=N, byrow = T)
  
    G[,current_start:current_end] = round((G1 + G2)/2 - k)
  
    l_g1 = l_g1 + c(sweep(sweep(G1[,], FUN = '-', STATS=2*probs, MARGIN = 2), FUN='/',
                                           STATS=sqrt(2*probs*(1-probs)), MARGIN = 2)  %*% beta_cut)
    l_g2 = l_g2 + c(sweep(sweep(G2[,], FUN = '-', STATS=2*probs, MARGIN = 2), FUN='/',
                                           STATS=sqrt(2*probs*(1-probs)), MARGIN = 2)  %*% beta_cut)
  
  }
  return(list('G'=G, 'l_g1'=l_g1, 'l_g2'=l_g2))
} 
```

```{r}
# Make liabilities
liabilities_func = function(G, MAF, beta, N=1e5, h_sq=0.5, block_size = 1000){
  l_g = rep(0, N)
  iterations = N/block_size

  for (i in 1:iterations){
    current_start = (i-1) * block_size + 1
    current_end = current_start + block_size - 1
    l_g[current_start:current_end] = c(sweep(sweep(G[current_start:current_end,], FUN = '-', STATS=2*MAF, MARGIN = 2), FUN='/',
                                           STATS=sqrt(2*MAF*(1-MAF)), MARGIN = 2)  %*% beta)

  }
  
  l_e = rnorm(N, 0, sqrt(1-h_sq))
  l_e1 = rnorm(N, 0, sqrt(1-h_sq))
  l_e2 = rnorm(N, 0, sqrt(1-h_sq))
  
  return(list('l_g'=l_g, 'l_e'=l_e, 'l_e1'=l_e1, 'l_e2'=l_e2))
}
```

```{r}
# Calculate who is sick
y_func = function(l_e, l_g, K=0.05) {
  l = l_g + l_e
  T_ = qnorm(1-K)
  y = ifelse(l>=T_, 1, 0)
  return(y)
}
```

```{r}
simulation = function (filename, h_sq=0.5, C=1000, K=0.05, N=1e5, M=1e5, block_size=1000) {
  # Make MAF
  MAF = runif(M, 0.01, 0.49)

  beta = beta_func(C, h_sq, M)
  G_l = G_func(filename, MAF, N, M, block_size)
  G = G_l$G
  l_g1 = G_l$l_g1
  l_g2 = G_l$l_g2
  l_g_e = liabilities_func(G, MAF, beta, N, h_sq, block_size)
  l_g = l_g_e$l_g
  l_e = l_g_e$l_e
  l_e1 = l_g_e$l_e1
  l_e2 = l_g_e$l_e2
  y = y_func(l_e, l_g, K)
  
  
  obj.bigsnp_LTFH = list(genotypes = G, # genotypes, FBM object
                  map = tibble(snp = 1:ncol(G), MAF, beta), # map, i.e. SNP info
                  fam = tibble(FID = 1:nrow(G), l_g, l_e, l_g1, l_e1, l_g2, l_e2)) # fam, i.e. info on individuals

  #saving the bigsnp object
  snp_save(obj.bigsnp_LTFH)
  
}

```

```{r}
simulation("test_parent_2", C=100, N=1000, M=1000, block_size = 100)
```


