---
title: "Simulation_family"
output: html_document
---
```{r}
library(bigsnpr)
library(dplyr)
```



```{r}
get_names <- function(values, n_sib=0, id= TRUE, parents=TRUE){
  
  len = length(values)
  prefix = c(rep("", len*id), rep("p",len*2*parents), rep("s",n_sib*len))
  
  n_peop = 1*id + 2*parents + n_sib
  index = c(rep(0,id), rep(c(1:2),parents), rep(c(3:(2+n_sib)),n_sib!=0))
  
  name = rep("", len*(n_peop))
  j = 1
  for (i in 1:n_peop){
    name[j:(j+len-1)] = paste0((paste(values,prefix[j:(j+len-1)], sep="_")), rep(index[i], len))
    j = j + len
  }
  return(name)
}

```



```{r}
# Make beta
beta_func = function(C=1000, h_sq=0.5, M=1e5){
  beta = rep(0, M)
  beta[sample(M,C)] = rnorm(C, 0, sqrt(h_sq/C))
  return (beta)
}

```


```{r}
# Make G
G_func = function(filename, beta, MAF, n_sib = 0, N=1e5, M=1e5, block_size=1000){
  G = FBM.code256(nrow = N,
                    ncol = M,
                    code = c(0L, 1L, 2L, rep(NA_integer_, 256 - 3)),
                    backingfile = filename)
  
  
  l_g_p1 = rep(0, M)
  l_g_p2 = rep(0, M)
  
  iterations = M/block_size
  
  for (i in n_sib){
  l_g_sibs = matrix(rep(0, M*n_sib), ncol = n_sib)
  }
  
  for(i in 1:iterations){
    current_start = (i-1) * block_size + 1
    current_end = current_start + block_size - 1
  
    probs = MAF[current_start:current_end]
    beta_cut = beta[current_start:current_end]
  
    G1 = matrix(rbinom(block_size*N, 2, probs), ncol=block_size, nrow=N, byrow = T)
    G2 = matrix(rbinom(block_size*N, 2, probs), ncol=block_size, nrow=N, byrow = T)
    k = matrix(rnorm(block_size*N, 0, 0.0000001), ncol=block_size, nrow=N, byrow = T)
  
    G[,current_start:current_end] = round((G1 + G2)/2 - k)
  
    l_g_p1 = l_g_p1 + c(sweep(sweep(G1[,], FUN = '-', STATS=2*probs, MARGIN = 2), FUN='/',
                                           STATS=sqrt(2*probs*(1-probs)), MARGIN = 2)  %*% beta_cut)
    l_g_p2 = l_g_p2 + c(sweep(sweep(G2[,], FUN = '-', STATS=2*probs, MARGIN = 2), FUN='/',
                                           STATS=sqrt(2*probs*(1-probs)), MARGIN = 2)  %*% beta_cut)
    
    if (n_sib != 0){
    for (i in 1:n_sib){
      k = matrix(rnorm(block_size*N, 0, 0.0000001), ncol=block_size, nrow=N, byrow = T)
      Gs = round((G1 + G2)/2 - k)
      temp = c(sweep(sweep(Gs[,], FUN = '-', STATS=2*probs, MARGIN = 2), FUN='/',
                                           STATS=sqrt(2*probs*(1-probs)), MARGIN = 2)  %*% beta_cut)
      l_g_sibs[,i] =  l_g_sibs[,i] + temp
    }
    }
  }
   if (n_sib != 0){
  out = list('G'=G, 'l_g_p1'=l_g_p1, 'l_g_p2'=l_g_p2, "l_g_sibs" = l_g_sibs)
   }
  else{
    out = list('G'=G, 'l_g_p1'=l_g_p1, 'l_g_p2'=l_g_p2)
  }
  return(out)
}
```

```{r}
# Make liabilities
liabilities_func = function(G, MAF, beta, n_sib = 0, N=1e5, h_sq=0.5, block_size = 1000){
  l_g_0 = rep(0, N)
  iterations = N/block_size

  for (i in 1:iterations){
    current_start = (i-1) * block_size + 1
    current_end = current_start + block_size - 1
    l_g_0[current_start:current_end] = c(sweep(sweep(G[current_start:current_end,], FUN = '-', STATS=2*MAF, MARGIN = 2), FUN='/',
                                           STATS=sqrt(2*MAF*(1-MAF)), MARGIN = 2)  %*% beta)

  }
  
  l_e_0 = rnorm(N, 0, sqrt(1-h_sq))
  l_e_p1 = rnorm(N, 0, sqrt(1-h_sq))
  l_e_p2 = rnorm(N, 0, sqrt(1-h_sq))
  
  if (n_sib != 0){
  l_e_sibs = matrix(rnorm(N * n_sib, 0, sqrt(1-h_sq)), ncol = n_sib)
    return(list('l_g_0'=l_g_0, 'l_e_0'=l_e_0, 'l_e_p1'=l_e_p1, 'l_e_p2'=l_e_p2, "l_e_sibs"
                = l_e_sibs))
  }
  else{
  return(list('l_g_0'=l_g_0, 'l_e_0'=l_e_0, 'l_e_p1'=l_e_p1, 'l_e_p2'=l_e_p2))
  }
}
```


```{r}
simulation = function (filename, h_sq=0.5, n_sib = 0, C=1000, K=0.05, N=1e5, M=1e5, block_size=1000) {
  # Make MAF
  MAF = runif(M, 0.01, 0.49)
  beta = beta_func(C, h_sq, M)
  G_l = G_func(filename, beta, MAF, n_sib, N, M, block_size)
  G = G_l$G
  l_g_p1 = G_l$l_g_p1
  l_g_p2 = G_l$l_g_p2
  l_g_e = liabilities_func(G, MAF, beta, n_sib, N, h_sq, block_size)
  l_g_0 = l_g_e$l_g_0
  l_e_0 = l_g_e$l_e_0
  l_e_p1 = l_g_e$l_e_p1
  l_e_p2 = l_g_e$l_e_p2
  if (n_sib != 0){
    l_g_sibs = G_l$l_g_sibs
    l_e_sibs = l_g_e$l_e_sibs
  }
  
  

  if (n_sib != 0){
    
   col_names_g = get_names(c("l_g"), id=FALSE, parents = FALSE, n_sib)
   col_names_e = get_names(c("l_e"), id=FALSE, parents = FALSE, n_sib)
   order = get_names(c("l_g","l_e"), id=FALSE, parents = FALSE, n_sib) 
   

   
   colnames(l_g_sibs) = col_names_g
   
   colnames(l_e_sibs) = col_names_e
   #print(l_e_sibs)
   
   l_all_sibs = as_tibble(cbind(l_g_sibs,l_e_sibs)) %>% relocate(order)
   #print(l_all_sibs)
    
   obj.bigsnp = list(genotypes = G, # genotypes, FBM object
                  map = tibble(snp = 1:ncol(G), MAF, beta), # map, i.e. SNP info
                  fam = bind_cols(tibble(FID = 1:nrow(G), l_g_0, l_e_0, l_g_p1, l_e_p1, l_g_p2,
                               l_e_p2), l_all_sibs)) # fam, i.e. info on individuals
   }
   else{
   obj.bigsnp = list(genotypes = G, # genotypes, FBM object
                  map = tibble(snp = 1:ncol(G), MAF, beta), # map, i.e. SNP info
                  fam = tibble(FID = 1:nrow(G), l_g_0, l_e_0, l_g_p1, l_e_p1, l_g_p2, l_e_p2))   
   }
   #saving the bigsnp object
   snp_save(obj.bigsnp)
  
}

```

```{r}
simulation("test", C=100, N=1000, M=1000, n_sib = 2, block_size = 100)
```


